version: "3"
services:
  lb:
    build: .
    container_name: lb
    ports:
      - "9006:9006"
    command: --backends "http://web1:80,http://web2:80"
  web1:
    image: strm/helloworld-http
  web2:
    image: strm/helloworld-http