name: Build-image
on:
  push:
    branches: 
      - main
  pull_request:
jobs:
  build-and-push-image:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image and push to Docker Hub
        uses:  docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: elsn/simple-lb:0.1.0 elsn/simple-lb:latest